#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace tinysearch {

// A single indexed document. `id` is a stable, deterministic identifier
// derived from the document's path (see index_store.h / hash_path()) so that
// re-indexing the same file always produces the same id.
struct Document {
    std::string id;
    std::string path;
    std::string title;
    std::string content;
    std::size_t token_count = 0;
    std::int64_t modified_time = 0;  // st_mtime at scan time, used for incremental indexing
};

// Lightweight metadata kept for every indexed document. We do not keep the
// full `content` in the persisted index / in memory after indexing, since it
// would bloat RAM and disk usage for no benefit to ranking. Snippets are
// regenerated by re-reading the file from disk on demand.
struct DocumentMeta {
    std::string id;
    std::string path;
    std::string title;
    std::uint32_t token_count = 0;
    std::int64_t modified_time = 0;
};

}  // namespace tinysearch
